import TextBox from '@/Components/Common/TextBox';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import hacker from '../../public/Naruto-hacker.png';
import pro from '../../public/Naruto-noob.png';
import noob from '../../public/Naruto-pro.png';

const Container = styled.main`
   height: 1600px;
   box-sizing: border-box;
`;

const SubContainer = styled.div`
   position: relative;
   z-index: 2;
   width: 100%;
   height: 100vh;
   display: flex;
   align-items: center;
   justify-content: center;
   flex-direction: column;
   box-sizing: border-box;
`;

const BackgroundImage = styled.div`
   position: absolute;
   width: 100%;
   height: 100%;
   top: 0px;
   left: 0px;
   z-index: -1;
   background-color: rgba(0, 0, 0, 0.5);
   background-image: url('./thumbnail3.png');
   background-size: cover;
   filter: blur(3px);
   background-blend-mode: darken;
`;

const TopContainer = styled.div`
   display: flex;
   flex-direction: column;
   width: 1058px;
   padding-bottom: 0px;
   color: white;
`;

const Category = styled.ul`
   display: flex;
   gap: 35px;
   margin: 0px;
   margin-top: 40px;
   margin-bottom: 60px;
   font-weight: 500;

   > li {
      text-align: center;
      list-style: none;
      font-size: 18px;
      color: #ddd;
   }

   > li:first-child {
      color: white;
      text-decoration: underline;
      text-underline-offset: 10px;
      text-decoration-color: #b84040;
   }
`;

const MainContainer = styled.div`
   display: flex;
   align-items: center;
   box-sizing: border-box;
   gap: 49px;

   > div {
      padding-bottom: 20px;
      backdrop-filter: blur(5px);

      > img:hover {
         cursor: pointer;
         scale: 1.02;
      }
   }
`;

const ContentContainer = styled.div`
   display: flex;
   align-items: center;
   margin-top: 10px;
   justify-content: space-between;
`;

const Content = styled.div`
   flex: 1;
   margin-left: 20px;
   display: flex;
   gap: 7px;
   flex-direction: column;
`;

const Divider = styled.div`
   width: 1px;
   height: 100%;
   background-color: #cacaca;
`;

const BBox = styled.ul`
   display: flex;
   justify-content: center;
   align-items: flex-end;
   width: 100%;
   gap: 15px;

   > li {
      display: flex;
      justify-content: center;
      border-radius: 10px;
      font-size: 24px;
      font-weight: 500;
      color: white;
   }

   > li:nth-child(2) {
      color: #646464;
      font-size: 16px;
   }
`;

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Container>
            <BackgroundImage />
            <SubContainer>
               <TopContainer>
                  <TextBox
                     text="제 4회"
                     fontSize="28px"
                     fontWeight="500"
                     lineHeight="36px"
                     margin="0px 0px 5px 0px"
                     color="#868686"
                  />
                  <TextBox text="눕프로해커 : 나루토 편" fontSize="36px" fontWeight="500" lineHeight="48px" />
                  <Category>
                     <Divider />
                     <li>가아라</li>
                     <Divider />
                     <li>오로치마루</li>
                     <Divider />
                     <li>카카시</li>
                     <Divider />
                     <li>사스케</li>
                     <Divider />
                     <li>나루토</li>
                     <Divider />
                  </Category>
               </TopContainer>
               <MainContainer>
                  <div>
                     <Image src={noob} width={320} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
                  <div>
                     <Image src={pro} width={320} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
                  <div>
                     <Image src={hacker} width={320} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
               </MainContainer>
            </SubContainer>
         </Container>
      </>
   );
}
