import TextBox from '@/components/TextBox';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import thumbnail1 from '../../public/thumbnail.png';
import thumbnail2 from '../../public/thumbnail2.png';
import thumbnail3 from '../../public/thumbnail3.png';

const Container = styled.main`
   width: 100%;
   height: 100vh;
   padding-top: 80px;
   background-color: rgba(0, 0, 0, 0.7);
   background-image: url('./thumbnail3.png');
   background-size: cover;
   background-blend-mode: darken;
   margin: 0px auto;
   display: flex;
   align-items: center;
   justify-content: center;
   padding-bottom: 280px;
   box-sizing: border-box;
`;

const SubContainer = styled.div`
   display: flex;
   flex-direction: column;
   align-items: center;
   box-sizing: border-box;
`;
const TopContainer = styled.div`
   display: flex;
   flex-direction: column;
   width: 1580px;
   padding-bottom: 0px;
   color: white;
`;

const Category = styled.ul`
   display: flex;
   gap: 45px;
   margin: 0px;
   margin-top: 40px;
   margin-bottom: 60px;
   font-weight: 500;

   > li {
      list-style: none;
      font-size: 20px;
      color: #ddd;
   }

   > li:first-child {
      color: white;
      text-decoration: underline;
      text-underline-offset: 10px;
      text-decoration-color: #b84040;
   }
`;

const MainContainer = styled.div`
   display: flex;
   align-items: center;
   box-sizing: border-box;
   gap: 35px;
`;

const ContentContainer = styled.div`
   display: flex;
   align-items: center;
   margin-top: 10px;
   justify-content: space-between;
`;

const TierBox = styled.span`
   display: flex;
   justify-content: center;
   align-items: center;
   width: 100px;
   height: 60px;
   border-radius: 10px;
   font-size: 18px;
   color: white;
   background-color: #c760a3;
`;

const Content = styled.div`
   flex: 1;
   margin-left: 20px;
   display: flex;
   gap: 7px;
   flex-direction: column;
`;

const BBox = styled.ul`
   display: flex;
   justify-content: center;
   align-items: flex-end;
   width: 100%;
   gap: 15px;

   > li {
      display: flex;
      justify-content: center;
      border-radius: 10px;
      font-size: 24px;
      font-weight: 500;
      color: white;
   }

   > li:nth-child(2) {
      color: #646464;
      font-size: 16px;
   }
`;

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Container>
            <SubContainer>
               <TopContainer>
                  <TextBox
                     text="제 24회"
                     fontSize="32px"
                     fontWeight="500"
                     lineHeight="44px"
                     margin="0px 0px 5px 0px"
                     color="#868686"
                  />
                  <TextBox text="눕프로해커" fontSize="42px" fontWeight="500" lineHeight="54px" />
                  <Category>
                     <li>미스포츈</li>
                     <li>파이크</li>
                     <li>요네</li>
                     <li>마스터 이</li>
                     <li>이즈리얼</li>
                  </Category>
               </TopContainer>
               <MainContainer>
                  <div>
                     <Image src={thumbnail1} width={500} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
                  <div>
                     <Image src={thumbnail2} width={500} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
                  <div>
                     <Image src={thumbnail3} width={500} alt="noob" />
                     <ContentContainer>
                        <Content>
                           <BBox>
                              <li>닼발</li>
                              <li>오마카세</li>
                           </BBox>
                        </Content>
                     </ContentContainer>
                  </div>
               </MainContainer>
            </SubContainer>
         </Container>
      </>
   );
}
