import Head from 'next/head';
import styled from 'styled-components';

import bg from '../../public/main-bg.webp';
import ContentsNav from '@/components/Main/ContentsNav';
import Contents from '@/components/Main/Contents';

const Layout = styled.main`
   height: 1600px;
   box-sizing: border-box;
`;

const ContentsBox = styled.div`
   position: relative;
   z-index: 2;
   width: 100%;
   height: 100vh;
   display: flex;
   justify-content: center;
   align-items: center;
   flex-direction: column;
   box-sizing: border-box;
`;

const BackgroundImage = styled.div`
   position: absolute;
   width: 100%;
   height: 100%;
   top: 0px;
   left: 0px;
   z-index: -1;
   background-color: rgba(0, 0, 0, 0.6);
   background-size: cover;
   background-position: center;
   background-blend-mode: darken;
   filter: blur(2px);
`;

export default function Home() {
   return (
      <>
         <Head>
            <title>Wakcraft</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Layout>
            <BackgroundImage style={{ backgroundImage: `url(${bg.src})` }} />
            <ContentsBox>
               <ContentsNav />
               <Contents />
            </ContentsBox>
         </Layout>
      </>
   );
}
